# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# site overview stuff
title: HF-ITCNE24-SemArbeit_-___-______ # After "Semesterarbeit" add the number of the semester, then the Subject and the name of the project
email: max.mustermann@contoso.ch # Add your email address here, if you want to be contacted by email

description: >- # this means to ignore newlines until another declaration. Add a short description of your project here. This will be shown in the meta tags of the HTML files.
  "Test description" 

# personal stuff
author: ""
github_username:  ""

# external stuff
aux_links:
  Projektplanung: # Add your Project pannintg link here
aux_links_new_tab: true


# technical site stuff
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "" # Add your logo here, if you have one. This will be shown in the top left corner of the page.
favicon_ico: "" # Add your favicon here, if you have one. This will be shown in the browser tab.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-feed
back_to_top: true
back_to_top_text: "Back to top"

exclude:
# Enter path with to exclude a file
  # For example, if you want to exclude the file "Logininfos.json" in the folder "ressources/scripts/"
  - ressources/notizen/
  - documentation/Hauptteil/Notizen_aufbau.md
  - ressources/scripts/Logininfos.json
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
